package com.example.a501_09.myportfolio_chungnam.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.example.a501_09.myportfolio_chungnam.db.Trip;
import com.example.a501_09.myportfolio_chungnam.db.Schedule;
import com.example.a501_09.myportfolio_chungnam.db.Place;

import com.example.a501_09.myportfolio_chungnam.db.TripDao;
import com.example.a501_09.myportfolio_chungnam.db.ScheduleDao;
import com.example.a501_09.myportfolio_chungnam.db.PlaceDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig tripDaoConfig;
    private final DaoConfig scheduleDaoConfig;
    private final DaoConfig placeDaoConfig;

    private final TripDao tripDao;
    private final ScheduleDao scheduleDao;
    private final PlaceDao placeDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        tripDaoConfig = daoConfigMap.get(TripDao.class).clone();
        tripDaoConfig.initIdentityScope(type);

        scheduleDaoConfig = daoConfigMap.get(ScheduleDao.class).clone();
        scheduleDaoConfig.initIdentityScope(type);

        placeDaoConfig = daoConfigMap.get(PlaceDao.class).clone();
        placeDaoConfig.initIdentityScope(type);

        tripDao = new TripDao(tripDaoConfig, this);
        scheduleDao = new ScheduleDao(scheduleDaoConfig, this);
        placeDao = new PlaceDao(placeDaoConfig, this);

        registerDao(Trip.class, tripDao);
        registerDao(Schedule.class, scheduleDao);
        registerDao(Place.class, placeDao);
    }
    
    public void clear() {
        tripDaoConfig.clearIdentityScope();
        scheduleDaoConfig.clearIdentityScope();
        placeDaoConfig.clearIdentityScope();
    }

    public TripDao getTripDao() {
        return tripDao;
    }

    public ScheduleDao getScheduleDao() {
        return scheduleDao;
    }

    public PlaceDao getPlaceDao() {
        return placeDao;
    }

}
